/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import java.awt.FileDialog;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.LinkOption.NOFOLLOW_LINKS;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.COPY_ATTRIBUTES;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELVIN
 */
public class Anaform extends javax.swing.JFrame {

    JFrame frame = new JFrame();
    FileDialog  file = new FileDialog(frame, "Qeyd yeri seç",FileDialog.SAVE);
        
    Path copy_from_1;
    Path copy_to_1;
        
        
        
    public Anaform() {
        initComponents();
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        
        jMenu1.setEnabled(false);
        jMenu2.setEnabled(false);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("workfiles.png")));
        this.setTitle("My files");
        
        if(Giris.icaze.equals("Admin")){
            jMenu1.setEnabled(true);
            jMenu2.setEnabled(true);
            
        }else if(Giris.icaze.equals("menecer")){
            jMenu1.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAxtar = new javax.swing.JTextField();
        btnAxtar = new javax.swing.JButton();
        textYukle = new javax.swing.JTextField();
        btnYukle = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cedvel = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAxtar.setText("Fayl axtar");
        btnAxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAxtarActionPerformed(evt);
            }
        });

        btnYukle.setText("Yükle");
        btnYukle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYukleActionPerformed(evt);
            }
        });

        cedvel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fayl adı", "Sahibi", "Tarixi", "İzzahı", "id", "yol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cedvel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedvelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cedvel);
        if (cedvel.getColumnModel().getColumnCount() > 0) {
            cedvel.getColumnModel().getColumn(4).setMinWidth(0);
            cedvel.getColumnModel().getColumn(4).setMaxWidth(0);
            cedvel.getColumnModel().getColumn(5).setMinWidth(0);
            cedvel.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jMenu1.setText("Fayl");

        jMenuItem1.setText("Yüklə");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Dəyişdir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Səlahiyyət");

        jMenuItem3.setText("İstifadəçi işləmləri");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textYukle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textAxtar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAxtar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnYukle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(textAxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAxtar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textYukle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYukle)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAxtarActionPerformed
        axtar();
    }//GEN-LAST:event_btnAxtarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Yukle yukle = new Yukle();
        yukle.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cedvelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedvelMouseClicked
        DefaultTableModel tablo = (DefaultTableModel) cedvel.getModel();
        
        textYukle.setText(tablo.getValueAt(cedvel.getSelectedRow(), 0).toString());
        jTextField3.setText(tablo.getValueAt(cedvel.getSelectedRow(), 4).toString());
        jTextField4.setText(tablo.getValueAt(cedvel.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_cedvelMouseClicked

    private void btnYukleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYukleActionPerformed
        try
        {
            String fayl2 = textYukle.getText();
            String fayl1 = jTextField4.getText();
            file.setFile(fayl2);
            file.show();
            
            String fayl3 = fayl2.substring(fayl2.length()-4);
            String fayl4 = file.getFile().concat(fayl3);
            
            String deneme = (file.getDirectory() + file.getFile());
            
            copy_from_1 = Paths.get("file", fayl1);
            copy_to_1 = Paths.get(file.getDirectory(), fayl4);
            
            if(fayl1.isEmpty() || deneme.equals("nullnull"))
            {
                JOptionPane.showMessageDialog(null,"Fayl Secilmedi","Xəta",-1);
            }
            else
            {
                Files.copy(copy_from_1, copy_to_1, REPLACE_EXISTING,COPY_ATTRIBUTES, NOFOLLOW_LINKS);
                JOptionPane.showMessageDialog(null,"Fayl Kopyalandı","Uğurlu",-1);
                textYukle.getText();
                jTextField4.getText();
                jTextField4.getText();
                
            }
        }
        catch(HeadlessException | IOException e){
            
        }
        
    }//GEN-LAST:event_btnYukleActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Deyisdir deyisdir = new Deyisdir();
        deyisdir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Istifadeci istifadeci = new Istifadeci();
        istifadeci.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anaform().setVisible(true);
            }
        });
    }
    
    
    public void axtar()
    {
        String axtar = textAxtar.getText();
        DefaultTableModel tablo = (DefaultTableModel) cedvel.getModel();
        int setir = tablo.getRowCount();
        for(int i = setir -1; i>=0; i--)
        {
            tablo.removeRow(i);
        }
        
             String sql = "SELECT * FROM fayllar where fayl like '%"+axtar+"%' and ok like 'Aktiv'";
             InsertApp con = new InsertApp();
        
              try (Connection conn = con.connect();
                   Statement stmt  = conn.createStatement();
                   ResultSet rs    = stmt.executeQuery(sql)){
                  
                  
                  while (rs.next()) {
                      int idAl = rs.getInt("id");
                        String faylAl = rs.getString("fayl");
                        String sahibiAl = rs.getString("sahibi");
                        String tarixAl = rs.getString("tarix");
                        String izzahAl = rs.getString("izzahi");
                        String fayl2Al = faylAl.substring(20);
                        tablo.addRow(new Object[]{fayl2Al, sahibiAl, tarixAl, izzahAl, idAl, faylAl});
                 
                    }
                } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"Məlumat yüklənərkən xata baş verdi","Xəta",-1);
                  }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAxtar;
    private javax.swing.JButton btnYukle;
    private javax.swing.JTable cedvel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField textAxtar;
    private javax.swing.JTextField textYukle;
    // End of variables declaration//GEN-END:variables
}
