/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELVIN
 */
public class Deyisdir extends javax.swing.JFrame {

    InsertApp app = new InsertApp();
    public Deyisdir() {
        initComponents();
        
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("workfiles.png")));
        this.setTitle("My files");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAxtar = new javax.swing.JTextField();
        btnAxtar = new javax.swing.JButton();
        textYukle = new javax.swing.JTextField();
        btnAktiv = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cedvel = new javax.swing.JTable();
        btnPassiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAxtar.setText("Fayl axtar");
        btnAxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAxtarActionPerformed(evt);
            }
        });

        btnAktiv.setText("Aktiv");
        btnAktiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktivActionPerformed(evt);
            }
        });

        cedvel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fayl adı", "Sahibi", "Tarixi", "İzzahı", "id", "yol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cedvel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedvelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cedvel);
        if (cedvel.getColumnModel().getColumnCount() > 0) {
            cedvel.getColumnModel().getColumn(4).setMinWidth(0);
            cedvel.getColumnModel().getColumn(4).setMaxWidth(0);
            cedvel.getColumnModel().getColumn(5).setMinWidth(0);
            cedvel.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        btnPassiv.setText("Passiv");
        btnPassiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textYukle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textAxtar, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAxtar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAktiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPassiv)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAxtar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textYukle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAktiv)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAxtarActionPerformed
        axtar();
    }//GEN-LAST:event_btnAxtarActionPerformed

    private void cedvelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedvelMouseClicked
        DefaultTableModel tablo = (DefaultTableModel) cedvel.getModel();
        
        textYukle.setText(tablo.getValueAt(cedvel.getSelectedRow(), 0).toString());
        jTextField3.setText(tablo.getValueAt(cedvel.getSelectedRow(), 4).toString());
        jTextField4.setText(tablo.getValueAt(cedvel.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_cedvelMouseClicked

    private void btnAktivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktivActionPerformed
        try{
            String id = jTextField3.getText();
            app.update("Aktiv", id);
            JOptionPane.showMessageDialog(null,"Işləm uğurlu şəkildə yerinə yetirildi","Xəta",-1);
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null,"Məlumat yüklənərkən xata baş verdi","Xəta",-1);
        }
    }//GEN-LAST:event_btnAktivActionPerformed

    private void btnPassivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassivActionPerformed
        try{
            String id = jTextField3.getText();
            app.update("Passiv", id);
            JOptionPane.showMessageDialog(null,"Işləm uğurlu şəkildə yerinə yetirildi","Xəta",-1);
        }
        catch(HeadlessException e){
            JOptionPane.showMessageDialog(null,"Məlumat yüklənərkən xata baş verdi","Xəta",-1);
        }
    }//GEN-LAST:event_btnPassivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deyisdir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deyisdir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deyisdir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deyisdir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deyisdir().setVisible(true);
            }
        });
    }
    
    public void axtar()
    {
        
        String axtar = textAxtar.getText();
        DefaultTableModel tablo = (DefaultTableModel) cedvel.getModel();
            int setir = tablo.getRowCount();
            for(int i = setir -1; i>=0; i--)
              {
                 tablo.removeRow(i);
              }
        
             String sql = "SELECT * FROM fayllar where fayl like '%"+axtar+"%'";
             InsertApp con = new InsertApp();
        
              try (Connection conn = con.connect();
                   Statement stmt  = conn.createStatement();
                   ResultSet rs    = stmt.executeQuery(sql)){
                  
                  
                  while (rs.next()) {
                      int idAl = rs.getInt("id");
                        String faylAl = rs.getString("fayl");
                        String sahibiAl = rs.getString("sahibi");
                        String tarixAl = rs.getString("tarix");
                        String izzahAl = rs.getString("izzahi");
                        String fayl2Al = faylAl.substring(20);
                        tablo.addRow(new Object[]{fayl2Al, sahibiAl, tarixAl, izzahAl, idAl, faylAl});
                 
                    }
                } catch (SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null,"Məlumat yüklənərkən xata baş verdi","Xəta",-1);
                 }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktiv;
    private javax.swing.JButton btnAxtar;
    private javax.swing.JButton btnPassiv;
    private javax.swing.JTable cedvel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField textAxtar;
    private javax.swing.JTextField textYukle;
    // End of variables declaration//GEN-END:variables
}
